name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    if: github.repository == 'mogic-le/t3x-changelog-info'

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - uses: CSchoel/release-notes-from-changelog@v1

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        body_path: RELEASE.md